CREATE TABLE players(playerID INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30));
CREATE TABLE lists(listID INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100));
CREATE TABLE players_lists(playerID INT, listID INT, PRIMARY KEY (playerID, listID), FOREIGN KEY (playerID) REFERENCES players(playerID), FOREIGN KEY (listID) REFERENCES lists(listID));