INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (0,18,'Schellen',1,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (1,20,'Rot',1,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (2,22,'Gruen',1,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (3,23,'Null',0,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (4,24,'Eichel',1,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (5,27,'Schellen',1,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (6,27,'Schellen',1,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (7,27,'Schellen',2,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (8,30,'Rot',1,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (9,30,'Rot',1,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (10,30,'Rot',2,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (11,33,'Gruen',1,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (12,33,'Gruen',1,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (13,33,'Gruen',2,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (14,35,'Null',0,1,'Hand');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (15,36,'Schellen',1,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (16,36,'Schellen',1,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (17,36,'Schellen',2,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (18,36,'Schellen',2,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (19,36,'Schellen',3,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (20,36,'Eichel',1,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (21,36,'Eichel',1,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (22,36,'Eichel',2,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (23,40,'Rot',1,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (24,40,'Rot',1,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (25,40,'Rot',2,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (26,40,'Rot',2,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (27,40,'Rot',3,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (28,44,'Gruen',1,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (29,44,'Gruen',1,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (30,44,'Gruen',2,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (31,44,'Gruen',2,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (32,44,'Gruen',3,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (33,45,'Schellen',1,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (34,45,'Schellen',1,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (35,45,'Schellen',2,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (36,45,'Schellen',2,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (37,45,'Schellen',3,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (38,45,'Schellen',3,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (39,45,'Schellen',4,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (40,46,'Null ouvert',0,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (41,48,'Eichel',1,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (42,48,'Eichel',1,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (43,48,'Eichel',2,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (44,48,'Eichel',2,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (45,48,'Eichel',3,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (46,48,'Grand',1,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (47,50,'Rot',1,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (48,50,'Rot',1,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (49,50,'Rot',2,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (50,50,'Rot',2,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (51,50,'Rot',3,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (52,50,'Rot',3,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (53,50,'Rot',4,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (54,54,'Schellen',1,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (55,54,'Schellen',2,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (56,54,'Schellen',2,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (57,54,'Schellen',3,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (58,54,'Schellen',3,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (59,54,'Schellen',4,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (60,54,'Schellen',4,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (61,54,'Schellen',5,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (62,55,'Gruen',1,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (63,55,'Gruen',1,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (64,55,'Gruen',2,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (65,55,'Gruen',2,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (66,55,'Gruen',3,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (67,55,'Gruen',3,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (68,55,'Gruen',4,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (69,59,'Null ouvert',0,1,'Hand');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (70,60,'Rot',1,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (71,60,'Rot',2,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (72,60,'Rot',2,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (73,60,'Rot',3,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (74,60,'Rot',3,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (75,60,'Rot',4,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (76,60,'Rot',4,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (77,60,'Rot',5,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (78,60,'Eichel',1,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (79,60,'Eichel',1,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (80,60,'Eichel',2,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (81,60,'Eichel',2,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (82,60,'Eichel',3,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (83,60,'Eichel',3,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (84,60,'Eichel',4,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (85,63,'Schellen',1,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (86,63,'Schellen',2,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (87,63,'Schellen',3,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (88,63,'Schellen',3,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (89,63,'Schellen',4,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (90,63,'Schellen',4,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (91,63,'Schellen',5,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (92,63,'Schellen',5,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (93,63,'Schellen',6,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (94,66,'Gruen',1,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (95,66,'Gruen',2,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (96,66,'Gruen',2,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (97,66,'Gruen',3,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (98,66,'Gruen',3,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (99,66,'Gruen',4,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (100,66,'Gruen',4,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (101,66,'Gruen',5,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (102,70,'Rot',1,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (103,70,'Rot',2,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (104,70,'Rot',3,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (105,70,'Rot',3,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (106,70,'Rot',4,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (107,70,'Rot',4,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (108,70,'Rot',5,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (109,70,'Rot',5,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (110,70,'Rot',6,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (111,72,'Schellen',1,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (112,72,'Schellen',2,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (113,72,'Schellen',3,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (114,72,'Schellen',4,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (115,72,'Schellen',4,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (116,72,'Schellen',5,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (117,72,'Schellen',5,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (118,72,'Schellen',6,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (119,72,'Schellen',6,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (120,72,'Schellen',7,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (121,72,'Eichel',1,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (122,72,'Eichel',2,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (123,72,'Eichel',2,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (124,72,'Eichel',3,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (125,72,'Eichel',3,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (126,72,'Eichel',4,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (127,72,'Eichel',4,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (128,72,'Eichel',5,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (129,72,'Grand',1,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (130,72,'Grand',1,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (131,72,'Grand',2,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (132,77,'Gruen',1,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (133,77,'Gruen',2,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (134,77,'Gruen',3,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (135,77,'Gruen',3,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (136,77,'Gruen',4,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (137,77,'Gruen',4,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (138,77,'Gruen',5,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (139,77,'Gruen',5,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (140,77,'Gruen',6,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (141,80,'Rot',1,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (142,80,'Rot',2,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (143,80,'Rot',3,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (144,80,'Rot',4,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (145,80,'Rot',4,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (146,80,'Rot',5,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (147,80,'Rot',5,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (148,80,'Rot',6,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (149,80,'Rot',6,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (150,80,'Rot',7,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (151,81,'Schellen',2,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (152,81,'Schellen',3,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (153,81,'Schellen',4,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (154,81,'Schellen',5,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (155,81,'Schellen',5,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (156,81,'Schellen',6,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (157,81,'Schellen',6,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (158,81,'Schellen',7,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (159,81,'Schellen',7,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (160,81,'Schellen',8,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (161,84,'Eichel',1,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (162,84,'Eichel',2,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (163,84,'Eichel',3,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (164,84,'Eichel',3,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (165,84,'Eichel',4,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (166,84,'Eichel',4,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (167,84,'Eichel',5,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (168,84,'Eichel',5,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (169,84,'Eichel',6,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (170,88,'Gruen',1,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (171,88,'Gruen',2,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (172,88,'Gruen',3,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (173,88,'Gruen',4,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (174,88,'Gruen',4,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (175,88,'Gruen',5,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (176,88,'Gruen',5,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (177,88,'Gruen',6,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (178,88,'Gruen',6,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (179,88,'Gruen',7,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (180,90,'Schellen',3,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (181,90,'Schellen',4,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (182,90,'Schellen',5,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (183,90,'Schellen',6,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (184,90,'Schellen',6,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (185,90,'Schellen',7,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (186,90,'Schellen',7,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (187,90,'Schellen',8,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (188,90,'Schellen',8,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (189,90,'Schellen',9,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (190,90,'Rot',2,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (191,90,'Rot',3,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (192,90,'Rot',4,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (193,90,'Rot',5,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (194,90,'Rot',5,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (195,90,'Rot',6,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (196,90,'Rot',6,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (197,90,'Rot',7,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (198,90,'Rot',7,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (199,90,'Rot',8,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (200,96,'Eichel',1,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (201,96,'Eichel',2,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (202,96,'Eichel',3,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (203,96,'Eichel',4,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (204,96,'Eichel',4,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (205,96,'Eichel',5,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (206,96,'Eichel',5,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (207,96,'Eichel',6,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (208,96,'Eichel',6,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (209,96,'Eichel',7,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (210,96,'Grand',1,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (211,96,'Grand',1,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (212,96,'Grand',2,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (213,96,'Grand',2,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (214,96,'Grand',3,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (215,99,'Schellen',4,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (216,99,'Schellen',5,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (217,99,'Schellen',6,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (218,99,'Schellen',7,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (219,99,'Schellen',7,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (220,99,'Schellen',8,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (221,99,'Schellen',8,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (222,99,'Schellen',9,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (223,99,'Schellen',9,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (224,99,'Schellen',10,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (225,99,'Gruen',2,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (226,99,'Gruen',3,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (227,99,'Gruen',4,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (228,99,'Gruen',5,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (229,99,'Gruen',5,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (230,99,'Gruen',6,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (231,99,'Gruen',6,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (232,99,'Gruen',7,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (233,99,'Gruen',7,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (234,99,'Gruen',8,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (235,100,'Rot',3,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (236,100,'Rot',4,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (237,100,'Rot',5,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (238,100,'Rot',6,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (239,100,'Rot',6,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (240,100,'Rot',7,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (241,100,'Rot',7,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (242,100,'Rot',8,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (243,100,'Rot',8,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (244,100,'Rot',9,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (245,108,'Schellen',5,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (246,108,'Schellen',6,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (247,108,'Schellen',7,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (248,108,'Schellen',8,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (249,108,'Schellen',8,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (250,108,'Schellen',9,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (251,108,'Schellen',9,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (252,108,'Schellen',10,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (253,108,'Schellen',10,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (254,108,'Schellen',11,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (255,108,'Eichel',2,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (256,108,'Eichel',3,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (257,108,'Eichel',4,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (258,108,'Eichel',5,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (259,108,'Eichel',5,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (260,108,'Eichel',6,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (261,108,'Eichel',6,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (262,108,'Eichel',7,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (263,108,'Eichel',7,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (264,108,'Eichel',8,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (265,110,'Rot',4,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (266,110,'Rot',5,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (267,110,'Rot',6,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (268,110,'Rot',7,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (269,110,'Rot',7,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (270,110,'Rot',8,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (271,110,'Rot',8,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (272,110,'Rot',9,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (273,110,'Rot',9,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (274,110,'Rot',10,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (275,110,'Gruen',3,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (276,110,'Gruen',4,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (277,110,'Gruen',5,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (278,110,'Gruen',6,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (279,110,'Gruen',6,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (280,110,'Gruen',7,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (281,110,'Gruen',7,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (282,110,'Gruen',8,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (283,110,'Gruen',8,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (284,110,'Gruen',9,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (285,117,'Schellen',6,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (286,117,'Schellen',7,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (287,117,'Schellen',8,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (288,117,'Schellen',9,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (289,117,'Schellen',9,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (290,117,'Schellen',10,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (291,117,'Schellen',10,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (292,117,'Schellen',11,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (293,117,'Schellen',11,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (294,120,'Rot',5,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (295,120,'Rot',6,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (296,120,'Rot',7,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (297,120,'Rot',8,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (298,120,'Rot',8,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (299,120,'Rot',9,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (300,120,'Rot',9,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (301,120,'Rot',10,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (302,120,'Rot',10,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (303,120,'Rot',11,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (304,120,'Eichel',3,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (305,120,'Eichel',4,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (306,120,'Eichel',5,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (307,120,'Eichel',6,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (308,120,'Eichel',6,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (309,120,'Eichel',7,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (310,120,'Eichel',7,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (311,120,'Eichel',8,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (312,120,'Eichel',8,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (313,120,'Eichel',9,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (314,120,'Grand',1,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (315,120,'Grand',1,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (316,120,'Grand',2,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (317,120,'Grand',2,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (318,120,'Grand',3,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (319,120,'Grand',3,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (320,120,'Grand',4,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (321,121,'Gruen',4,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (322,121,'Gruen',5,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (323,121,'Gruen',6,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (324,121,'Gruen',7,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (325,121,'Gruen',7,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (326,121,'Gruen',8,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (327,121,'Gruen',8,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (328,121,'Gruen',9,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (329,121,'Gruen',9,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (330,121,'Gruen',10,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (331,126,'Schellen',7,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (332,126,'Schellen',8,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (333,126,'Schellen',9,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (334,126,'Schellen',10,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (335,126,'Schellen',10,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (336,126,'Schellen',11,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (337,126,'Schellen',11,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (338,130,'Rot',6,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (339,130,'Rot',7,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (340,130,'Rot',8,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (341,130,'Rot',9,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (342,130,'Rot',9,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (343,130,'Rot',10,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (344,130,'Rot',10,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (345,130,'Rot',11,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (346,130,'Rot',11,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (347,132,'Gruen',5,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (348,132,'Gruen',6,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (349,132,'Gruen',7,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (350,132,'Gruen',8,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (351,132,'Gruen',8,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (352,132,'Gruen',9,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (353,132,'Gruen',9,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (354,132,'Gruen',10,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (355,132,'Gruen',10,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (356,132,'Gruen',11,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (357,132,'Eichel',4,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (358,132,'Eichel',5,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (359,132,'Eichel',6,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (360,132,'Eichel',7,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (361,132,'Eichel',7,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (362,132,'Eichel',8,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (363,132,'Eichel',8,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (364,132,'Eichel',9,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (365,132,'Eichel',9,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (366,132,'Eichel',10,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (367,135,'Schellen',8,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (368,135,'Schellen',9,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (369,135,'Schellen',10,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (370,135,'Schellen',11,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (371,135,'Schellen',11,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (372,140,'Rot',7,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (373,140,'Rot',8,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (374,140,'Rot',9,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (375,140,'Rot',10,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (376,140,'Rot',10,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (377,140,'Rot',11,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (378,140,'Rot',11,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (379,143,'Gruen',6,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (380,143,'Gruen',7,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (381,143,'Gruen',8,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (382,143,'Gruen',9,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (383,143,'Gruen',9,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (384,143,'Gruen',10,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (385,143,'Gruen',10,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (386,143,'Gruen',11,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (387,143,'Gruen',11,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (388,144,'Schellen',9,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (389,144,'Schellen',10,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (390,144,'Schellen',11,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (391,144,'Eichel',5,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (392,144,'Eichel',6,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (393,144,'Eichel',7,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (394,144,'Eichel',8,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (395,144,'Eichel',8,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (396,144,'Eichel',9,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (397,144,'Eichel',9,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (398,144,'Eichel',10,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (399,144,'Eichel',10,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (400,144,'Eichel',11,1,'Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (401,144,'Grand',1,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (402,144,'Grand',2,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (403,144,'Grand',2,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (404,144,'Grand',3,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (405,144,'Grand',3,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (406,144,'Grand',4,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (407,144,'Grand',4,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (408,150,'Rot',8,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (409,150,'Rot',9,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (410,150,'Rot',10,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (411,150,'Rot',11,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (412,150,'Rot',11,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (413,153,'Schellen',10,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (414,153,'Schellen',11,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (415,154,'Gruen',7,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (416,154,'Gruen',8,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (417,154,'Gruen',9,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (418,154,'Gruen',10,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (419,154,'Gruen',10,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (420,154,'Gruen',11,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (421,154,'Gruen',11,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (422,156,'Eichel',6,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (423,156,'Eichel',7,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (424,156,'Eichel',8,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (425,156,'Eichel',9,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (426,156,'Eichel',9,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (427,156,'Eichel',10,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (428,156,'Eichel',10,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (429,156,'Eichel',11,2,'Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (430,156,'Eichel',11,2,'Hand Einfach');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (431,160,'Rot',9,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (432,160,'Rot',10,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (433,160,'Rot',11,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (434,162,'Schellen',11,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (435,165,'Gruen',8,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (436,165,'Gruen',9,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (437,165,'Gruen',10,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (438,165,'Gruen',11,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (439,165,'Gruen',11,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (440,168,'Eichel',7,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (441,168,'Eichel',8,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (442,168,'Eichel',9,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (443,168,'Eichel',10,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (444,168,'Eichel',10,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (445,168,'Eichel',11,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (446,168,'Eichel',11,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (447,168,'Grand',1,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (448,168,'Grand',2,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (449,168,'Grand',3,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (450,168,'Grand',3,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (451,168,'Grand',4,3,'Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (452,168,'Grand',4,3,'Hand Schneider');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (453,170,'Rot',10,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (454,170,'Rot',11,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (455,176,'Gruen',9,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (456,176,'Gruen',10,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (457,176,'Gruen',11,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (458,180,'Rot',11,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (459,180,'Eichel',8,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (460,180,'Eichel',9,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (461,180,'Eichel',10,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (462,180,'Eichel',11,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (463,180,'Eichel',11,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (464,187,'Gruen',10,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (465,187,'Gruen',11,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (466,192,'Eichel',9,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (467,192,'Eichel',10,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (468,192,'Eichel',11,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (469,192,'Grand',1,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (470,192,'Grand',2,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (471,192,'Grand',3,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (472,192,'Grand',4,4,'Hand Schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (473,192,'Grand',4,4,'Hand Schneider angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (474,198,'Gruen',11,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (475,204,'Eichel',10,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (476,204,'Eichel',11,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (477,216,'Eichel',11,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (478,216,'Grand',2,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (479,216,'Grand',3,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (480,216,'Grand',4,5,'Hand Schneider angesagt, schwarz');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (481,240,'Grand',3,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (482,240,'Grand',4,6,'Hand Schwarz angesagt');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (483,264,'Grand',4,7,'Offen');
INSERT INTO possibleGames(gameID, score, typeName, peaks, modifierValue, modifierName) VALUES (484,20, 'Ramsch',0,1, 'Einfach');

--CREATE TABLE played_games(gameID INT  AUTO_INCREMENT PRIMARY KEY, playedGameID INT, playerID INT, listID INT, hasWon BOOL, time DATETIME, FOREIGN KEY (playedGameID) REFERENCES possibleGames(gameID), FOREIGN KEY (playerID) REFERENCES players(playerID), FOREIGN KEY (listID) REFERENCES lists(listID));